services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    volumes:
      - /mnt/docker/kavita/config:/config
      - /media:/media
    ports:
      - 5000:5000
    networks:
      - default
      - proxy
      - media
    restart: unless-stopped

networks:
  default:
  proxy:
    external: true
  media:
    external: true