services:
  ente-museum:
    image: ghcr.io/ente-io/server
    container_name: ente-museum
    networks: 
      - default
      - proxy
    depends_on:
      ente-db:
        condition: service_healthy
    volumes:
      - /home/fern/docker/data/ente-photos/config/museum.yaml:/museum.yaml:ro
      - /home/fern/docker/data/ente-photos/data:/data:ro
    healthcheck:
      test: ["CMD", "curl", "--fail", "https://api.ente.fern.garden/ping"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      caddy: api.ente.fern.garden
      caddy.reverse_proxy: '{{upstreams 8080}}'

  ente-socat:
    image: alpine/socat
    container_name: ente-socat
    network_mode: service:ente-museum
    depends_on: [ente-museum]
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:ente-minio:3200"

  ente-web:
    image: ghcr.io/ente-io/web
    container_name: ente-web
    networks:
      - default
      - proxy
    environment:
      ENTE_API_ORIGIN: https://api.ente.fern.garden
      ENTE_ALBUMS_ORIGIN: https://albums.ente.fern.garden
    labels:
      caddy_1: ente.fern.garden
      caddy_1.reverse_proxy: '{{upstreams 3000}}'
      caddy_2: albums.ente.fern.garden
      caddy_2.reverse_proxy: '{{upstreams 3002}}'

  ente-db:
    image: postgres:15
    container_name: ente-db
    environment:
      POSTGRES_USER: ente
      POSTGRES_PASSWORD: ${ENTE_DB_PASSWORD}
      POSTGRES_DB: ente
    networks:
      - default
    healthcheck:
      test: pg_isready -q -d ente -U ente
      start_period: 40s
      start_interval: 1s
    volumes:
      - /home/fern/docker/data/ente-photos/db:/var/lib/postgresql/data

  ente-minio:
    image: minio/minio
    container_name: ente-minio
    networks:
      - default
      - proxy
    environment:
      MINIO_ROOT_USER: ente
      MINIO_ROOT_PASSWORD: ${ENTE_MINIO_ROOT_PASSWORD}
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - /home/fern/docker/data/ente-photos/storage:/data
    labels:
      caddy: s3.ente.fern.garden
      caddy.reverse_proxy: '{{upstreams 3200}}'
    post_start:
      - command: |
          sh -c '
          #!/bin/sh

          while ! mc alias set h0 https://s3.ente.fern.garden ente ${ENTE_MINIO_ROOT_PASSWORD} 2>/dev/null
          do
            echo "Waiting for minio..."
            sleep 0.5
          done

          cd /data

          mc mb -p b2-eu-cen
          mc mb -p wasabi-eu-central-2-v3
          mc mb -p scw-eu-fr-v3
          '

networks:
  default:
  proxy:
    external: true
