name: qbittorrent
services:
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    depends_on:
      - qbittorrent
    volumes:
      - /home/fern/docker/data/qbittorrent/cross-seed/config:/config
      - /media:/media
    networks:
      - default
      - media
    command: daemon
    restart: unless-stopped
    user: 1000:1800

  fertilizer:
    image: ghcr.io/moleculekayak/fertilizer:latest
    container_name: fertilizer
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - qbittorrent
    volumes:
      - /home/fern/docker/data/qbittorrent/qbittorrent/config:/torrents:ro
      - /media:/media
    environment:
      - OPS_KEY=${OPS_KEY}
      - RED_KEY=${RED_KEY}
      - INJECT_TORRENTS=true
      - INJECTION_LINK_DIRECTORY=/media/downloads/fertilizer/linked-data
      - QBITTORRENT_URL=http://fern:${QBITTORRENT_PASS}@qbittorrent:8080
    command: fertilizer -o /media/downloads/fertilizer/torrent-files -i /torrents/qBittorrent/BT_backup --server
    user: 1000:1800
  
  qbittorrent:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrent
    volumes:
      - /home/fern/docker/data/qbittorrent/qbittorrent/config:/config
      - /home/fern/docker/data/qbittorrent/qbittorrent/data:/data
      - /media:/media
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=protonvpn
      - VPN_CLIENT=openvpn
      - VPN_USER=${PROTON_USER}+pmp
      - VPN_PASS=${PROTON_PASS}
      - STRICT_PORT_FORWARD=yes
      - NAME_SERVERS=9.9.9.9
      - LAN_NETWORK=10.0.1.0/24,172.16.0.0/24
      - ENABLE_PRIVOXY=yes
      - PUID=1000
      - PGID=1800
      - WEBUI_PORT=8080
      - VPN_INPUT_PORTS=8080
      - UMASK=000
      - DEBUG=false
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      caddy: qbittorrent.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 8080}}"

  qbittorrent_mamapi:
    image: elforkhead/mamapi:latest
    container_name: qbittorrent_mamapi
    restart: unless-stopped
    depends_on:
      - qbittorrent
    volumes:
      - /home/fern/docker/data/qbittorrent/mamapi/data:/data
    networks:
      - default
    environment:
      TZ: Australia/Perth
      MAM_ID: ${MAM_ID}
      WRITE_CURRENT_MAMID: True

networks:
  default:
  proxy:
    external: true
  media:
    external: true
