name: wallosf
services:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    volumes:
      - /home/fern/docker/data/wallos/database:/var/www/html/db
      - /home/fern/docker/data/wallos/logos:/var/www/html/images/uploads/logos
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      caddy: subscriptions.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: "authentik_proxy:9000"

networks:
  default:
  proxy:
    external: true
