name: caddy
services:
  caddy:
    image: ghcr.io/firewalkwithm3/caddy:latest
    container_name: caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files:/etc/caddy
      - /srv:/srv
      - /home/fern/docker/data/caddy/data:/data
    environment:
      - CADDY_INGRESS_NETWORKS=proxy
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    networks:
      - default
      - proxy
    restart: unless-stopped

networks:
  default:
  proxy:
    external: true
