services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
      - /media:/media
    environment:
      - TZ=Australia/Perth
    labels:
      caddy: audiobooks.fern.garden
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  default:
  proxy:
    external: true

volumes:
  audiobookshelf_config:
    name: audiobookshelf_config
  audiobookshelf_metadata:
    name: audiobookshelf_metadata
