name: audiobookshelf

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - /home/fern/docker/data/audiobookshelf/config:/config
      - /home/fern/docker/data/audiobookshelf/metadata:/metadata
      - /media:/media
    environment:
      - TZ=Australia/Perth
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      caddy: audiobooks.fern.garden
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  default:
  proxy:
    external: true
