name: komga
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - komga_config:/config
      - /media:/media:ro
    environment:
      - TZ=Australia/Perth
      - KOMGA_OAUTH2_ACCOUNT_CREATION=true
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: comics.fern.garden
      caddy.reverse_proxy: '{{upstreams 25600}}'
    user: "1000:1800"

networks:
  default:
  media:
    external: true
  proxy:
    external: true

volumes:
  komga_config:
    name: komga_config
