name: 13ft

services:
  13ft:
    image: ghcr.io/wasi-master/13ft:latest
    container_name: 13ft
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      caddy: 13ft.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 5000 }}'

networks:
  default:
  proxy:
    external: true
