name: go2rtc
services:
  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Australia/Perth
    volumes:
      - /home/fern/docker/data/go2rtc/config:/config

