name: navidrome
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    volumes:
      - navidrome_data:/data
      - /media/media/beets:/music:ro
    environment:
      - ND_BASEURL=https://music.fern.garden
      - ND_REVERSEPROXYUSERHEADER=X-authentik-username
      - ND_REVERSEPROXYWHITELIST=0.0.0.0/0
      - ND_LASTFM_APIKEY=${ND_LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${ND_LASTFM_SECRET}
      - ND_PLAYLISTSPATH=Playlists
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: music.fern.garden
      caddy.import: authentik

  explo:
    image: ghcr.io/lumepart/explo:latest
    restart: unless-stopped
    container_name: explo
    volumes:
      - ./explo.env:/opt/explo/.env
      - /media/media/beets/explo:/data/
      - /media/downloads/slskd/downloads:/slskd/
    networks:
      - default
      - media
    environment:
      - TZ=Australia/Perth
      - CRON_SCHEDULE=00 07 * * 1 # Runs weekly, every Monday at 07:00

networks:
  default:
  media:
    external: true
  proxy:
    external: true

volumes:
  navidrome_data:
    name: navidrome_data
