name: forgejo
services:
  forgejo_db:
    image: postgres:14
    container_name: forgejo_db
    volumes:
      - /home/fern/docker/data/forgejo/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_DB=forgejo
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - default
    restart: unless-stopped
  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    depends_on:
      - forgejo_db
    volumes:
      - /home/fern/docker/data/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=forgejo_db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=${POSTGRES_PASSWORD}
    ports:
      - '222:22'
    networks:
      - proxy
      - default
    restart: unless-stopped
    labels:
      caddy: git.fern.garden
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  default:
  proxy:
    external: true
