services:
  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    networks:
      - proxy
      - default
    ports:
      - 222:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=forgejo_db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - forgejo_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - forgejo_db
    labels:
      caddy: git.fern.garden
      caddy.reverse_proxy: "{{upstreams 3000}}"

  forgejo_db:
    image: postgres:14
    container_name: forgejo_db
    networks:
      - default
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_DB=forgejo
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - forgejo_db:/var/lib/postgresql/data

networks:
  default:
  proxy:
    external: true

volumes:
  forgejo_data:
    name: forgejo_data
  forgejo_db:
    name: forgejo_db
