name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /home/fern/docker/data/homepage/config:/app/config
      - /media:/media:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: dash.ferngarden.net
    networks:
      - default
      - proxy
      - metrics
    restart: unless-stopped
    labels:
      caddy: dash.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 3000 }}'

networks:
  proxy:
    external: true
  metrics:
    external: true
