name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /mnt/docker/homepage/config:/app/config
    environment:
      HOMEPAGE_ALLOWED_HOSTS: dash.ferngarden.net
    networks:
      - default
      - proxy
      - metrics
    restart: unless-stopped
    labels:
      caddy: dash.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 3000 }}'
    user: 1000:1000

networks:
  proxy:
    external: true
  metrics:
    external: true
