name: grocy
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    volumes:
      - grocy_config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
      - GROCY_FEATURE_FLAG_RECIPES=false
      - GROCY_FEATURE_FLAG_SHOPPINGLIST=false
      - GROCY_FEATURE_FLAG_STOCK=false
      - GROCY_CURRENCY=AUD
    ports:
      - '9192:80'
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      caddy: grocy.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  default:
  proxy:
    external: true

volumes:
  grocy_config:
    name: grocy_config
