name: netatalk
services:
  netatalk:
    image: netatalk/netatalk:latest
    container_name: netatalk
    volumes:
      - netatalk_backup:/mnt/afpbackup
      - /srv/netatalk:/mnt/afpshare
      - /var/run/dbus:/var/run/dbus
    environment:
      - AFP_USER=fern
      - AFP_PASS=${AFP_PASS}
      - AFP_GROUP=afpusers
      - ATALKD_INTERFACE=eth0
      - TZ=Australia/Perth
    network_mode: host
    cap_add:
      - NET_ADMIN

volumes:
  netatalk_backup:
