name: scrutiny
services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    volumes:
      - /run/udev:/run/udev:ro
      - /home/fern/docker/data/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /home/fern/docker/data/scrutiny/config:/opt/scrutiny/config
    networks:
      - default
      - proxy
    labels:
      caddy: scrutiny.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 8080 }}'
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sdc
      - /dev/sdd
      - /dev/sde

networks:
  default:
  proxy:
    external: true
  metrics:
    external: true
