services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    cap_add: 
      - SYS_RAWIO
    volumes:
      - /run/udev:/run/udev:ro
      - /mnt/docker/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /mnt/docker/scrutiny/config:/opt/scrutiny/config
    devices:
      - /dev/disk/by-uuid/fcee0188-8ca1-4fda-81b7-f5920c79ab48
      - /dev/disk/by-uuid/5d9dd538-79e4-4168-be91-e0b040155cb3
      - /dev/disk/by-uuid/5a43b7dc-3e28-459e-824a-ad45b5475361
    labels:
      caddy: scrutiny.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 8080 }}'

networks:
  default:
  proxy:
    external: true
  metrics:
    external: true