services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    volumes:
      - /mnt/docker/calibre-web-automated/config:/config 
      - /media/media/calibre/ingest:/cwa-book-ingest
      - /media/media/calibre/library:/calibre-library
    networks:
      - default
      - proxy
      - media
    labels:
      caddy: books.fern.garden
      caddy.reverse_proxy: '{{ upstreams 8083 }}'
    restart: unless-stopped

networks:
  default:
  proxy:
    external: true
  media:
    external: true
