name: calibre
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    volumes:
      - /home/fern/docker/data/calibre/config:/config
      - /media/media/calibre/ingest:/cwa-book-ingest
      - /media/media/calibre/library:/calibre-library
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    networks:
      - default
      - proxy
      - media
    restart: unless-stopped
    labels:
      caddy: books.fern.garden
      caddy.reverse_proxy: '{{ upstreams 8083 }}'

  # cwa-downloader:
  #   image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
  #   container_name: cwa-downloader
  #   volumes:
  #     - /media/media/calibre/ingest:/cwa-book-ingest
  #   environment:
  #     FLASK_PORT: 8084
  #     LOG_LEVEL: info
  #     BOOK_LANGUAGE: en
  #     USE_BOOK_TITLE: true
  #     TZ: Australia/Perth
  #     APP_ENV: prod
  #     UID: 1000
  #     GID: 1800
  #   networks:
  #     - default
  #     - media
  #     - proxy
  #   restart: unless-stopped
  #   labels:
  #     caddy: books-dl.ferngarden.net
  #     caddy.import: internal
  #     caddy.reverse_proxy: '{{ upstreams 8084 }}'

networks:
  default:
  proxy:
    external: true
  media:
    external: true
