services:
  linkwarden_db:
    image: postgres:16-alpine
    container_name: linkwarden_db
    environment:
      - POSTGRES_USER=linkwarden
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=linkwarden
    restart: always
    volumes:
      - /mnt/docker/linkwarden/database:/var/lib/postgresql/data
    networks:
      - default
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    environment:
      - DATABASE_URL=postgresql://linkwarden:${POSTGRES_PASSWORD}@linkwarden_db:5432/linkwarden
      - MEILI_HOST=linkwarden_search
      - NEXTAUTH_URL=https://linkwarden.ferngarden.net/api/v1/auth
    restart: always
    volumes:
      - /mnt/docker/linkwarden/data:/data/data
    depends_on:
      - linkwarden_db
      - linkwarden_search
    networks:
      - default
      - proxy
    labels:
      caddy: linkwarden.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 3000 }}'
  linkwarden_search:
    image: getmeili/meilisearch:v1.12.8
    container_name: linkwarden_search
    restart: always
    volumes:
      - /mnt/docker/linkwarden/search:/meili_data
    networks:
      - default

networks:
  default:
  proxy:
    external: true
