name: hortusfox
services:
  hortusfox:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    container_name: hortusfox
    depends_on:
      - hortusfox_db
    volumes:
      - /home/fern/docker/data/hortusfox/images:/var/www/html/public/img
      - /home/fern/docker/data/hortusfox/logs:/var/www/html/hortusfox/logs
      - /home/fern/docker/data/hortusfox/backup:/var/www/html/public/backup
      - /home/fern/docker/data/hortusfox/themes:/var/www/html/public/themes
      - /home/fern/docker/data/hortusfox/migrate:/var/www/html/hortusfox/migrations
    environment:
      APP_ADMIN_EMAIL: mail@fern.garden
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      APP_TIMEZONE: Australia/Perth
      DB_HOST: hortusfox_db
      DB_PORT: 3306
      DB_DATABASE: hortusfox
      DB_USERNAME: hortusfox
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_CHARSET: "utf8mb4"
    networks:
      - default
      - proxy
    labels:
      caddy: hortusfox.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 80}}"

  hortusfox_db:
    image: mariadb
    container_name: hortusfox_db
    volumes:
      - /home/fern/docker/data/hortusfox/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: hortusfox
      MYSQL_USER: hortusfox
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default
    restart: always

networks:
  default:
  proxy:
    external: true
