name: dozzle
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      DOZZLE_AUTH_PROVIDER: forward-proxy
      DOZZLE_REMOTE_HOST: tcp://docker_socket_proxy:2375|docker.local,tcp://10.0.1.101:2375|minecraft.local,tcp://10.0.1.4:2375|weebill.local
    networks:
      - default
      - metrics
      - proxy
    labels:
      caddy: dozzle.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

networks:
  default:
  metrics:
    external: true
  proxy:
    external: true
