name: dozzle
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      DOZZLE_AUTH_PROVIDER: forward-proxy
      DOZZLE_REMOTE_HOST: tcp://docker_socket_proxy:2375|'VM: docker',tcp://10.0.1.101:2375|'VM: minecraft',tcp://10.0.1.105:2375|'VM: musicbrainz'
    networks:
      - default
      - metrics
      - proxy
    labels:
      caddy: dozzle.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

networks:
  default:
  metrics:
    external: true
  proxy:
    external: true
