name: slskd
services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    volumes:
      - /mnt/docker/slskd/data:/app
      - /media:/media
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SHARED_DIR=/media/media/lidarr
      - SLSKD_DOWNLOADS_DIR=/media/downloads/slskd/downloads
      - SLSKD_INCOMPLETE_DIR=/media/downloads/slskd/incomplete
      - SLSKD_USERNAME=fern
      - SLSKD_PASSWORD=${SLSKD_PASSWORD}
      - SLSKD_SLSK_USERNAME=MtQueerie
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
    ports:
      - '50300:50300'
    networks:
      - default
      - proxy
      - media
    restart: unless-stopped
    labels:
      caddy: slskd.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 5030}}"
    user: 1000:1800

networks:
  default:
  proxy:
    external: true
  media:
    external: true
