name: minecraft
services:
  minecraft_proxy:
    image: itzg/mc-proxy
    container_name: minecraft_proxy
    volumes:
      - velocity_config:/config
      - velocity_server:/server
    environment:
      - TYPE=VELOCITY
      - MINECRAFT_VERSION=1.21.5
    ports:
      - '25565:25565'
    networks:
      - default
    restart: unless-stopped

  minecraft_server_bob:
    image: itzg/minecraft-server
    container_name: minecraft_server_bob
    depends_on:
      - minecraft_proxy
    volumes:
      - minecraft_server_bob:/data
    environment:
      - MOTD=it's bob's world, we're just living in it
      - ICON=https://git.fern.garden/fern/stacks/raw/branch/main/minecraft/server-icons/bob.png
    env_file:
      - server.env
    restart: unless-stopped
    hostname: bob

  minecraft_server_mc:
    image: itzg/minecraft-server
    container_name: minecraft_server_mc
    depends_on:
      - minecraft_proxy
    volumes:
      - minecraft_server_mc:/data
    environment:
      - MOTD=meow
      - ICON=https://git.fern.garden/fern/stacks/raw/branch/main/minecraft/server-icons/mc.png
      - PLUGINS=https://dev.bukkit.org/projects/dead-chest/files/latest
    env_file:
      - server.env
    networks:
      - default
    restart: unless-stopped
    hostname: mc

networks:
  default:


volumes:
  minecraft_webadmin_db:
    name: minecraft_webadmin_db
  minecraft_server_mc:
    name: minecraft_server_mc
  minecraft_server_bob:
    name: minecraft_server_bob
  velocity_config:
    name: velocity_config
  velocity_server:
    name: velocity_server
