name: minecraft
services:
  crafty-controller:
      container_name: crafty-controller
      image: registry.gitlab.com/crafty-controller/crafty-4:latest
      restart: always
      environment:
          - TZ=Australia/Perth
      ports:
          - "8443:8443" # HTTPS
          - "8123:8123" # DYNMAP
          - "25565:25565" # Java
      volumes:
          - /home/fern/docker/data/minecraft/crafty-controller/backups:/crafty/backups
          - /home/fern/docker/data/minecraft/crafty-controller/logs:/crafty/logs
          - /home/fern/docker/data/minecraft/crafty-controller/servers:/crafty/servers
          - /home/fern/docker/data/minecraft/crafty-controller/config:/crafty/app/config
          - /home/fern/docker/data/minecraft/crafty-controller/import:/crafty/import

networks:
  default:
