name: minecraft
services:
  crafty-controller:
      container_name: crafty-contraller
      image: registry.gitlab.com/crafty-controller/crafty-4:latest
      restart: always
      environment:
          - TZ=Australia/Perth
      ports:
          - "8443:8443" # HTTPS
          - "8123:8123" # DYNMAP
      volumes:
          - /home/fern/docker/data/minecraft/crafty-controller/backups:/crafty/backups
          - /home/fern/docker/data/minecraft/crafty-controller/logs:/crafty/logs
          - /home/fern/docker/data/minecraft/crafty-controller/servers:/crafty/servers
          - /home/fern/docker/data/minecraft/crafty-controller/config:/crafty/app/config
          - /home/fern/docker/data/minecraft/crafty-controller/import:/crafty/import
          
  minecraft_proxy:
    image: itzg/mc-proxy
    container_name: minecraft_proxy
    volumes:
      - /home/fern/docker/data/minecraft/velocity/config:/config
      - /home/fern/docker/data/minecraft/velocity/server:/server
    environment:
      - TYPE=VELOCITY
      - MINECRAFT_VERSION=1.21.5
    ports:
      - '25565:25565'
    networks:
      - default
    restart: unless-stopped
    user: 1000:100

  minecraft_server_bob:
    image: itzg/minecraft-server
    container_name: minecraft_server_bob
    depends_on:
      - minecraft_proxy
    volumes:
      - /home/fern/docker/data/minecraft/servers/bobworld:/data
    environment:
      - MOTD=it's bob's world, we're just living in it
      - ICON=https://git.fern.garden/fern/stacks/raw/branch/main/minecraft/server-icons/bob.png
    env_file:
      - server.env
    restart: unless-stopped
    hostname: bob
    user: 1000:100

  minecraft_server_mc:
    image: itzg/minecraft-server
    container_name: minecraft_server_mc
    depends_on:
      - minecraft_proxy
    volumes:
      - /home/fern/docker/data/minecraft/servers/mc:/data
    environment:
      - MOTD=meow
      - ICON=https://git.fern.garden/fern/stacks/raw/branch/main/minecraft/server-icons/mc.png
      - PLUGINS=https://dev.bukkit.org/projects/dead-chest/files/latest
    env_file:
      - server.env
    networks:
      - default
    restart: unless-stopped
    hostname: mc
    user: 1000:100

networks:
  default:
