name: minecraft
services:
  minecraft_proxy:
    image: itzg/mc-proxy
    container_name: minecraft_proxy
    volumes:
      - /home/fern/docker/data/minecraft/velocity/config:/config
      - /home/fern/docker/data/minecraft/velocity/server:/server
    environment:
      - TYPE=VELOCITY
      - MINECRAFT_VERSION=1.21.5
    ports:
      - '25565:25565'
    networks:
      - default
    restart: unless-stopped
    user: 1000:100

  minecraft_server_bob:
    image: itzg/minecraft-server
    container_name: minecraft_server_bob
    depends_on:
      - minecraft_proxy
    volumes:
      - /home/fern/docker/data/minecraft/servers/bobworld:/data
    environment:
      - MOTD=it's bob's world, we're just living in it
      - ICON=https://git.fern.garden/fern/stacks/raw/branch/main/minecraft/server-icons/bob.png
    env_file:
      - server.env
    restart: unless-stopped
    hostname: bob
    user: 1000:100

  minecraft_server_mc:
    image: itzg/minecraft-server
    container_name: minecraft_server_mc
    depends_on:
      - minecraft_proxy
    volumes:
      - /home/fern/docker/data/minecraft/servers/mc:/data
    environment:
      - MOTD=meow
      - ICON=https://git.fern.garden/fern/stacks/raw/branch/main/minecraft/server-icons/mc.png
      - PLUGINS=https://dev.bukkit.org/projects/dead-chest/files/latest
    env_file:
      - server.env
    networks:
      - default
    restart: unless-stopped
    hostname: mc
    user: 1000:100

networks:
  default:
