services:
  obsidian-livesync:
    image: couchdb:latest
    container_name: obsidian-livesync
    user: 1000:1000
    environment:
      - COUCHDB_USER=obsidian
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - /mnt/docker/obsidian-livesync/data:/opt/couchdb/data
      - /mnt/docker/obsidian-livesync/config:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    restart: unless-stopped