services:
  obsidian-livesync:
    image: couchdb:latest
    container_name: obsidian-livesync
    user: 1000:1000
    environment:
      - COUCHDB_USER=obsidian
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - /home/fern/docker/data/obsidian-livesync/data:/opt/couchdb/data
      - /home/fern/docker/data/obsidian-livesync/config:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    networks:
      - default
      - proxy
    labels:
      caddy: ols.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 5984 }}'
    restart: unless-stopped

networks:
  default:
  proxy:
    external: true   