name: arr

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - /home/fern/docker/data/bazarr/config:/config
      - /media:/media
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: bazarr.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    volumes:
      - /home/fern/docker/data/cleanuparr/config:/config
      - /media:/media
    environment:
      - TZ=Australia/Perth
      - PUID=1000
      - PGID=1800
    networks:
      - default
      - proxy
      - media
    restart: unless-stopped
    labels:
      caddy: cleanuparr.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 11011 }}'

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Australia/Perth
    networks:
      - default
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    volumes:
      - /home/fern/docker/data/jackett/config:/config
      - /home/fern/docker/data/jackett/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: jackett.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    volumes:
      - /home/fern/docker/data/jellyseerr/config:/app/config
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/Perth
    networks:
      - default
      - proxy
      - media
    restart: unless-stopped
    labels:
      caddy: jellyseerr.fern.garden
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 5055}}"

  kapowarr:
    image: mrcas/kapowarr:latest
    container_name: kapowarr
    volumes:
      - /home/fern/docker/data/kapowarr/database:/app/db
      - /media:/media
    networks:
      - default
      - media
      - proxy
    labels:
      caddy: kapowarr.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: '{{ upstreams 5656 }}'

  letterboxd-list-radarr:
    image: screeny05/letterboxd-list-radarr:latest
    container_name: letterboxd-list-radarr
    depends_on:
      - letterboxd-list-radarr_redis
    environment:
      - REDIS_URL=redis://letterboxd-list-radarr_redis:6379
    networks:
      - default
    restart: unless-stopped

  letterboxd-list-radarr_redis:
    image: redis:6.0
    container_name: letterboxd-list-radarr_redis
    volumes:
      - /home/fern/docker/data/letterboxd-list-radarr/redis:/data
    networks:
      - default
    restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver-labs/prarr:lidarr-plugins
    container_name: lidarr
    volumes:
      - /home/fern/docker/data/lidarr/config:/config
      - /home/fern/docker/data/beets/config:/beets
      - ./install_beets.bash:/custom-cont-init.d/install_beets.bash:ro
      - /media:/media
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: lidarr.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    volumes:
      - /home/fern/docker/data/profilarr/config:/config
    environment:
      - TZ=Australia/Perth
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: profilarr.ferngarden.net
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 6868}}"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - /home/fern/docker/data/prowlarr/config:/config
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: prowlarr.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /home/fern/docker/data/radarr/config:/config
      - /media:/media
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: radarr.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /home/fern/docker/data/sonarr/config:/config
      - /media:/media
    environment:
      - PUID=1000
      - PGID=1800
      - TZ=Australia/Perth
    networks:
      - default
      - media
      - proxy
    restart: unless-stopped
    labels:
      caddy: sonarr.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

  soularr:
    image: mrusse08/soularr:latest
    container_name: soularr
    volumes:
      - /media:/media
      - /home/fern/docker/data/soularr/config:/data
    environment:
      - TZ=Australia/Perth
      - SCRIPT_INTERVAL=300
    networks:
      - default
      - media
    restart: unless-stopped
    user: 1000:1800

networks:
  default:
  proxy:
    external: true
  media:
    name: media
