name: searxng
services:
  searxng_redis:
    container_name: searxng_redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - default
    volumes:
      - /home/fern/docker/data/searxng/redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - /home/fern/docker/data/searxng/config:/etc/searxng
      - /home/fern/docker/data/searxng/data:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=https://search.ferngarden.net
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  default:
  proxy:
    external: true
