name: stash
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/downloads/porn:/data:ro
      - /home/fern/docker/data/stash/config:/root/.stash
      - /home/fern/docker/data/stash/metadata:/metadata
      - /home/fern/docker/data/stash/cache:/cache
      - /home/fern/docker/data/stash/blobs:/blobs
      - /home/fern/docker/data/stash/generated:/generated
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_BLOBS=/blobs/
      - STASH_PORT=9999
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      caddy: stash.ferngarden.net
      caddy.1_import: internal
      caddy.2_import: authentik

networks:
  default:
  proxy:
    external: true
  media:
    external: true
